-- mani.lock.lua (auto-generated by mani, do not edit by hand!)
-- generated: 2026-06-17T20:29:46Z
return {
  lockfile_version = "1.0",
  manifest_hash = "7802b62c06c62ad879ffae62f7fd1e41b185c35be112744746fe96dd87fbbc34",
  packages = {
    ["argparse"] = {
      version = "0.7.2-1",
      source = "https://github.com/luarocks/argparse/archive/0.7.2.zip",
      hash = "ea4be33712df2efb29fe053dd8c660b1320beae409772cfed229194aff8ce7ab",
      integrity = "17d60f734b694a6c9d8e31e7f73247f471272e9dfb85017cd43514a9a922fc89",
      dependencies = {},
    },
    ["luasocket"] = {
      version = "3.1.0-1",
      source = "git+https://github.com/lunarmodules/luasocket.git",
      hash = "9974f72e2afdb60be0f1d642758903af98c3078a1ea99ff2914f7ccfca38e971",
      integrity = "fa9a2d5b4dc72da4b1d103ba7c8461aa0aed0a9187afd75fadc875a6352a7b5d",
      dependencies = {},
    },
    ["lunajson"] = {
      version = "1.2.3-1",
      source = "git://github.com/grafi-tt/lunajson.git",
      hash = "7739ba2c34379cdb84f34341635ecf937d1ebaa6b9eb98ebaa504e0d52f312ff",
      integrity = "cfda033aa0b1e22b8776c997c66e73e773149931f5dd5885d0fcea3b368be393",
      dependencies = {},
    },
  }
}